apiVersion: apps/v1
kind: Deployment
# namespace: default
metadata:
  name: bear-bank-deployment-${TARGET_ROLE}
  namespace: default
  labels:
    app: bear-bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bear-bank
  template:
    metadata:
      labels:
        app: bear-bank
        role: ${TARGET_ROLE}
    spec:
      containers:
      - name: bear-bank
        image: idreeskun/test-bear-image
        ports:
        - containerPort: 5000
        resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
