apiVersion: v1
kind: Service
metadata:
  name: bear-bank
  namespace: default
  labels:
    app: bear-bank
    role: rolling-update
spec:
  selector:
    app: bear-bank
    role: rolling-update
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 80
     targetPort: 5000
